import type { StageDef } from './stage';

// 10ステージ。パレット・広さ・密度・高低差で性格を変える。
// seedを変えない限りレイアウトは不変。
export const STAGES: StageDef[] = [
  {
    id: 'kunren',
    name: '訓練場',
    subtitle: '見通しの良い入門マップ',
    seed: 11,
    size: 60,
    obstacleCount: 14,
    maxHeight: 3,
    botCount: 4,
    palette: {
      sky: '#cfe8f5',
      fog: '#cfe8f5',
      floor: '#b8bcc4',
      wall: '#8d939e',
      obstacle: '#6e7686',
      accent: '#ff5a3c',
      lightColor: '#fff4e0',
      lightIntensity: 1.6,
      ambientIntensity: 0.9,
      fogDensity: 0.01,
      emissiveAccent: false,
      turbidity: 3,
      rayleigh: 1.5,
      mieCoefficient: 0.005,
      elevation: 45,
      azimuth: 180,
      exposure: 1.0,
      environmentIntensity: 0.9,
    },
  },
  {
    id: 'souko',
    name: '倉庫区',
    subtitle: 'コンテナの裏を取り合う近距離戦',
    seed: 23,
    size: 70,
    obstacleCount: 24,
    maxHeight: 4,
    botCount: 5,
    palette: {
      sky: '#9fb4c4',
      fog: '#9fb4c4',
      floor: '#7a7f86',
      wall: '#5d6066',
      obstacle: '#a8854f',
      accent: '#e8b53a',
      lightColor: '#f5ecd8',
      lightIntensity: 1.4,
      ambientIntensity: 0.8,
      fogDensity: 0.014,
      emissiveAccent: false,
      turbidity: 6,
      rayleigh: 2.0,
      mieCoefficient: 0.005,
      elevation: 32,
      azimuth: 150,
      exposure: 1.0,
      environmentIntensity: 0.8,
    },
  },
  {
    id: 'nakaniwa',
    name: '中庭',
    subtitle: '石組みと植え込みの回り込み合戦',
    seed: 37,
    size: 64,
    obstacleCount: 18,
    maxHeight: 3.4,
    botCount: 5,
    palette: {
      sky: '#bfe3ee',
      fog: '#c8e6e8',
      floor: '#7ba05f',
      wall: '#b06a4a',
      obstacle: '#c8b89a',
      accent: '#d9763c',
      lightColor: '#fff8e8',
      lightIntensity: 1.7,
      ambientIntensity: 0.95,
      fogDensity: 0.011,
      emissiveAccent: false,
      turbidity: 4,
      rayleigh: 1.5,
      mieCoefficient: 0.004,
      elevation: 50,
      azimuth: 200,
      exposure: 1.0,
      environmentIntensity: 0.85,
    },
  },
  {
    id: 'kairou',
    name: '回廊',
    subtitle: '柱の森を抜ける読み合い',
    seed: 41,
    size: 56,
    obstacleCount: 26,
    maxHeight: 3.6,
    botCount: 4,
    palette: {
      sky: '#f0e3c8',
      fog: '#ecdcbc',
      floor: '#cbb289',
      wall: '#b39767',
      obstacle: '#a08454',
      accent: '#6fb3c4',
      lightColor: '#ffeec8',
      lightIntensity: 1.5,
      ambientIntensity: 0.85,
      fogDensity: 0.016,
      emissiveAccent: false,
      turbidity: 8,
      rayleigh: 1.2,
      mieCoefficient: 0.006,
      elevation: 25,
      azimuth: 120,
      exposure: 0.95,
      environmentIntensity: 0.7,
    },
  },
  {
    id: 'kouwan',
    name: '港湾',
    subtitle: '長い射線が通る広域マップ',
    seed: 53,
    size: 78,
    obstacleCount: 24,
    maxHeight: 4.5,
    botCount: 6,
    palette: {
      sky: '#aac8dd',
      fog: '#aac8dd',
      floor: '#9aa1a8',
      wall: '#6b7780',
      obstacle: '#3f6e9e',
      accent: '#c4453a',
      lightColor: '#eef4fa',
      lightIntensity: 1.5,
      ambientIntensity: 0.85,
      fogDensity: 0.009,
      emissiveAccent: false,
      turbidity: 4,
      rayleigh: 1.8,
      mieCoefficient: 0.003,
      elevation: 20,
      azimuth: 100,
      exposure: 1.0,
      environmentIntensity: 0.85,
    },
  },
  {
    id: 'takadai',
    name: '高台',
    subtitle: '夕暮れの逆光を背負う丘',
    seed: 67,
    size: 66,
    obstacleCount: 16,
    maxHeight: 5,
    botCount: 5,
    palette: {
      sky: '#e8b08a',
      fog: '#d9a08c',
      floor: '#8d7f96',
      wall: '#6a5d7a',
      obstacle: '#54485f',
      accent: '#f0a35e',
      lightColor: '#ffb87a',
      lightIntensity: 1.3,
      ambientIntensity: 0.7,
      fogDensity: 0.015,
      emissiveAccent: false,
      turbidity: 9,
      rayleigh: 3.0,
      mieCoefficient: 0.005,
      elevation: 8,
      azimuth: 90,
      exposure: 1.05,
      environmentIntensity: 0.6,
      bloomStrength: 0.7,
    },
  },
  {
    id: 'sakyuu',
    name: '砂丘',
    subtitle: '遮蔽の少ない我慢比べ',
    seed: 71,
    size: 74,
    obstacleCount: 14,
    maxHeight: 3,
    botCount: 5,
    palette: {
      sky: '#eedfb8',
      fog: '#e8d6a8',
      floor: '#d9c08a',
      wall: '#c2a86e',
      obstacle: '#b08f5c',
      accent: '#3f9e97',
      lightColor: '#fff2d0',
      lightIntensity: 1.8,
      ambientIntensity: 1,
      fogDensity: 0.012,
      emissiveAccent: false,
      turbidity: 5,
      rayleigh: 1.0,
      mieCoefficient: 0.003,
      elevation: 60,
      azimuth: 180,
      exposure: 0.9,
      environmentIntensity: 0.9,
    },
  },
  {
    id: 'setsugen',
    name: '雪原',
    subtitle: '深い霧と白の迷彩',
    seed: 83,
    size: 70,
    obstacleCount: 18,
    maxHeight: 3.6,
    botCount: 5,
    palette: {
      sky: '#dce8f4',
      fog: '#e4edf6',
      floor: '#e8edf2',
      wall: '#c2ccd8',
      obstacle: '#9fb4cc',
      accent: '#4a7dbf',
      lightColor: '#eef4ff',
      lightIntensity: 1.2,
      ambientIntensity: 1,
      fogDensity: 0.028,
      emissiveAccent: false,
      turbidity: 1.5,
      rayleigh: 0.4,
      mieCoefficient: 0.001,
      elevation: 22,
      azimuth: 160,
      exposure: 0.95,
      environmentIntensity: 1.0,
    },
  },
  {
    id: 'koushou',
    name: '工廠',
    subtitle: '鉄骨密集の屋内型レイアウト',
    seed: 89,
    size: 62,
    obstacleCount: 28,
    maxHeight: 4.5,
    botCount: 6,
    palette: {
      sky: '#6b7077',
      fog: '#5d6166',
      floor: '#4a4d52',
      wall: '#3a3d42',
      obstacle: '#5d6166',
      accent: '#ff7a2e',
      lightColor: '#ffd9b0',
      lightIntensity: 1.1,
      ambientIntensity: 0.55,
      fogDensity: 0.02,
      emissiveAccent: true,
      turbidity: 12,
      rayleigh: 1.0,
      mieCoefficient: 0.01,
      elevation: 6,
      azimuth: 270,
      exposure: 1.05,
      environmentIntensity: 0.4,
    },
  },
  {
    id: 'yoichi',
    name: '夜市',
    subtitle: 'ネオンだけが頼りの夜戦',
    seed: 97,
    size: 58,
    obstacleCount: 24,
    maxHeight: 3.6,
    botCount: 5,
    palette: {
      sky: '#1a1c24',
      fog: '#22242e',
      floor: '#2e3138',
      wall: '#26282e',
      obstacle: '#3a3e48',
      accent: '#ff4f7a',
      lightColor: '#aab4ff',
      lightIntensity: 0.7,
      ambientIntensity: 0.4,
      fogDensity: 0.024,
      emissiveAccent: true,
      turbidity: 16,
      rayleigh: 0.6,
      mieCoefficient: 0.02,
      elevation: 5,
      azimuth: 270,
      exposure: 1.15,
      environmentIntensity: 0.45,
      bloomThreshold: 0.7,
    },
  },
];

export function stageById(id: string): StageDef {
  const def = STAGES.find((s) => s.id === id);
  if (!def) throw new Error(`unknown stage: ${id}`);
  return def;
}
