import type { StageDef } from './stage';

// 30ステージ(通常20 + ⑥ゾンビ専用10=z01〜z10)。パレット・広さ・密度・高低差で性格を変える。
// seedを変えない限りレイアウトは不変。
// 日差しの安全域: elevation 12〜62 / exposure 0.85〜1.15(Sky.jsの地平破綻と白飛び/黒潰れ回避)。
export const STAGES: StageDef[] = [
  {
    id: 'kunren',
    name: '訓練場',
    subtitle: '見通しの良い入門マップ',
    seed: 11,
    size: 60,
    obstacleCount: 14,
    maxHeight: 3,
    botCount: 4,
    palette: {
      sky: '#cfe8f5',
      fog: '#cfe8f5',
      floor: '#b8bcc4',
      wall: '#8d939e',
      obstacle: '#6e7686',
      accent: '#ff5a3c',
      mood: 'day',
      grassKind: 'none',
      particle: 'none',
      silhouette: 'skyline',
      lightColor: '#fff4e0',
      lightIntensity: 1.6,
      ambientIntensity: 0.9,
      fogDensity: 0.01,
      emissiveAccent: false,
      turbidity: 3,
      rayleigh: 1.5,
      mieCoefficient: 0.005,
      elevation: 45,
      azimuth: 180,
      // R13glare: 入門マップは最初に眩しさが問われる。明るい床+sun1.6で明部が飛ぶため
      // 露出を半段(1.0→0.96)引いて白飛りを抜く。直射/影の落ち方はsun不変で維持。
      exposure: 0.96,
      environmentIntensity: 0.9,
    },
  },
  {
    id: 'souko',
    name: '倉庫区',
    subtitle: 'コンテナの裏を取り合う近距離戦',
    seed: 23,
    size: 70,
    obstacleCount: 24,
    maxHeight: 4,
    botCount: 5,
    palette: {
      sky: '#9fb4c4',
      fog: '#9fb4c4',
      floor: '#7a7f86',
      wall: '#5d6066',
      obstacle: '#a8854f',
      accent: '#e8b53a',
      mood: 'overcast',
      grassKind: 'none',
      particle: 'dust',
      silhouette: 'skyline',
      groundFog: 0.35,
      lightColor: '#f5ecd8',
      lightIntensity: 1.4,
      ambientIntensity: 0.8,
      fogDensity: 0.014,
      emissiveAccent: false,
      turbidity: 6,
      rayleigh: 2.0,
      mieCoefficient: 0.005,
      elevation: 32,
      azimuth: 150,
      exposure: 1.0,
      environmentIntensity: 0.8,
    },
  },
  {
    id: 'nakaniwa',
    name: '中庭',
    subtitle: '石組みと植え込みの回り込み合戦',
    seed: 37,
    size: 64,
    obstacleCount: 18,
    maxHeight: 3.4,
    botCount: 5,
    palette: {
      sky: '#bfe3ee',
      fog: '#c8e6e8',
      floor: '#7ba05f',
      wall: '#b06a4a',
      obstacle: '#c8b89a',
      accent: '#d9763c',
      mood: 'day',
      grassKind: 'blade',
      grassDensity: 0.5,
      particle: 'none',
      silhouette: 'none',
      lightColor: '#fff8e8',
      lightIntensity: 1.7,
      ambientIntensity: 0.95,
      fogDensity: 0.011,
      emissiveAccent: false,
      turbidity: 4,
      rayleigh: 1.5,
      mieCoefficient: 0.004,
      elevation: 50,
      azimuth: 200,
      // R13glare: sun1.7の高照度で明部が飛ぶため露出を半段(1.0→0.97)引く。影は不変。
      exposure: 0.97,
      environmentIntensity: 0.85,
    },
  },
  {
    id: 'kairou',
    name: '回廊',
    subtitle: '柱の森を抜ける読み合い',
    seed: 41,
    size: 56,
    obstacleCount: 26,
    maxHeight: 3.6,
    botCount: 4,
    palette: {
      sky: '#f0e3c8',
      fog: '#ecdcbc',
      floor: '#cbb289',
      wall: '#b39767',
      obstacle: '#a08454',
      accent: '#6fb3c4',
      mood: 'overcast',
      grassKind: 'none',
      particle: 'dust',
      silhouette: 'skyline',
      groundFog: 0.35,
      lightColor: '#ffeec8',
      lightIntensity: 1.5,
      ambientIntensity: 0.85,
      fogDensity: 0.016,
      emissiveAccent: false,
      turbidity: 8,
      rayleigh: 1.2,
      mieCoefficient: 0.006,
      elevation: 25,
      azimuth: 120,
      exposure: 0.95,
      environmentIntensity: 0.7,
    },
  },
  {
    id: 'kouwan',
    name: '港湾',
    subtitle: '長い射線が通る広域マップ',
    seed: 53,
    size: 78,
    obstacleCount: 24,
    maxHeight: 4.5,
    botCount: 6,
    palette: {
      sky: '#aac8dd',
      fog: '#aac8dd',
      floor: '#9aa1a8',
      wall: '#6b7780',
      obstacle: '#3f6e9e',
      accent: '#c4453a',
      mood: 'overcast',
      grassKind: 'none',
      particle: 'dust',
      silhouette: 'skyline',
      groundFog: 0.3,
      lightColor: '#eef4fa',
      lightIntensity: 1.5,
      ambientIntensity: 0.85,
      fogDensity: 0.009,
      emissiveAccent: false,
      turbidity: 4,
      rayleigh: 1.8,
      mieCoefficient: 0.003,
      elevation: 20,
      azimuth: 100,
      exposure: 1.0,
      environmentIntensity: 0.85,
    },
  },
  {
    id: 'takadai',
    name: '高台',
    subtitle: '夕暮れの逆光を背負う丘',
    seed: 67,
    size: 66,
    obstacleCount: 16,
    maxHeight: 5,
    botCount: 5,
    palette: {
      sky: '#e8b08a',
      fog: '#d9a08c',
      floor: '#8d7f96',
      wall: '#6a5d7a',
      obstacle: '#54485f',
      accent: '#f0a35e',
      mood: 'dusk',
      grassKind: 'dry',
      grassDensity: 0.35,
      particle: 'dust',
      silhouette: 'ridge',
      groundFog: 0.35,
      lightColor: '#ffb87a',
      lightIntensity: 1.3,
      ambientIntensity: 0.7,
      fogDensity: 0.015,
      emissiveAccent: false,
      turbidity: 9,
      rayleigh: 3.0,
      mieCoefficient: 0.005,
      elevation: 12, // 監査修正: 8°はSky.jsの地平破綻域で「低い太陽なのに眩しい」矛盾が出るため安全域下限12°へ(夕暮れの雰囲気は維持)
      azimuth: 90,
      exposure: 1.05,
      environmentIntensity: 0.6,
      bloomStrength: 0.7,
    },
  },
  {
    id: 'sakyuu',
    name: '砂丘',
    subtitle: '遮蔽の少ない我慢比べ',
    seed: 71,
    size: 74,
    obstacleCount: 14,
    maxHeight: 3,
    botCount: 5,
    palette: {
      sky: '#eedfb8',
      fog: '#e8d6a8',
      floor: '#d9c08a',
      wall: '#c2a86e',
      obstacle: '#b08f5c',
      accent: '#3f9e97',
      mood: 'day',
      grassKind: 'dry',
      grassDensity: 0.35,
      particle: 'dust',
      particleAmount: 0.9,
      silhouette: 'mountain',
      groundFog: 0.3,
      lightColor: '#fff2d0',
      lightIntensity: 1.8,
      ambientIntensity: 1,
      fogDensity: 0.012,
      emissiveAccent: false,
      turbidity: 5,
      rayleigh: 1.0,
      mieCoefficient: 0.003,
      elevation: 60,
      azimuth: 180,
      exposure: 0.9,
      environmentIntensity: 0.9,
    },
  },
  {
    id: 'setsugen',
    name: '雪原',
    subtitle: '深い霧と白の迷彩',
    seed: 83,
    size: 70,
    obstacleCount: 18,
    maxHeight: 3.6,
    botCount: 5,
    palette: {
      sky: '#dce8f4',
      // R13 意図的な雪霧: near-white(#e4edf6)は地平が白飛びして「バグっぽい」白霞になる。
      // 銀青の霞へ。match側の sky-lerp後(≈#a9c5de/L0.77)に着地させ、中距離の敵が視認できる。
      fog: '#9cbcd8',
      floor: '#e8edf2',
      wall: '#c2ccd8',
      obstacle: '#9fb4cc',
      accent: '#4a7dbf',
      mood: 'snow',
      grassKind: 'snowtuft',
      grassDensity: 0.35,
      particle: 'snow',
      particleAmount: 1.0,
      silhouette: 'mountain',
      groundFog: 0.5,
      lightColor: '#eef4ff',
      lightIntensity: 1.2,
      ambientIntensity: 1,
      // R13: 0.028は中距離(30m)で50%も白霞に沈み敵が消える。0.018で30m≈25%まで緩和。
      fogDensity: 0.018,
      emissiveAccent: false,
      turbidity: 1.5,
      rayleigh: 0.4,
      mieCoefficient: 0.001,
      elevation: 22,
      azimuth: 160,
      exposure: 0.95,
      environmentIntensity: 0.85, // 監査修正: ほぼ白の床(#e8edf2)+ambient1.0にIBL1.0を重ねると白飛び域に入るため既定0.85へ抑制
    },
  },
  {
    id: 'koushou',
    name: '工廠',
    subtitle: '鉄骨密集の屋内型レイアウト',
    seed: 89,
    size: 62,
    obstacleCount: 28,
    maxHeight: 4.5,
    botCount: 6,
    palette: {
      sky: '#6b7077',
      fog: '#5d6166',
      floor: '#4a4d52',
      wall: '#3a3d42',
      obstacle: '#5d6166',
      accent: '#ff7a2e',
      mood: 'night',
      grassKind: 'none',
      particle: 'ember',
      silhouette: 'skyline',
      // R13: 足元の霧を薄め、鉄骨越しの敵シルエットを潰さない
      groundFog: 0.45,
      lightColor: '#ffd9b0',
      lightIntensity: 1.1,
      ambientIntensity: 0.55,
      fogDensity: 0.016,
      emissiveAccent: true,
      turbidity: 12,
      rayleigh: 1.0,
      mieCoefficient: 0.01,
      elevation: 12, // 監査修正: 6°は地平すれすれで空が破綻し露出1.05と矛盾するため安全域12°へ(turbidity12の濁りで薄暗さは維持)
      azimuth: 270,
      exposure: 1.05,
      environmentIntensity: 0.4,
    },
  },
  {
    id: 'yoichi',
    name: '夜市',
    subtitle: 'ネオンだけが頼りの夜戦',
    seed: 97,
    size: 58,
    obstacleCount: 24,
    maxHeight: 3.6,
    botCount: 5,
    palette: {
      sky: '#1a1c24',
      fog: '#22242e',
      floor: '#2e3138',
      wall: '#26282e',
      obstacle: '#3a3e48',
      accent: '#ff4f7a',
      mood: 'night',
      grassKind: 'none',
      particle: 'ember',
      silhouette: 'skyline',
      groundFog: 0.35,
      lightColor: '#aab4ff',
      lightIntensity: 0.7,
      ambientIntensity: 0.4,
      // R13: ネオンが霧に沈みすぎるのを緩和(夜市の視程を確保)
      fogDensity: 0.018,
      emissiveAccent: true,
      turbidity: 16,
      rayleigh: 0.6,
      mieCoefficient: 0.02,
      elevation: 12, // 監査修正: 5°+露出1.15の「低い太陽なのに眩しい」矛盾を解消。薄暮のネオン市場として安全域12°へ
      azimuth: 270,
      exposure: 1.1, // 監査修正: 露出も1.15→1.1へ半段下げ、ネオンの滲み(bloomThreshold0.7)は維持
      environmentIntensity: 0.45,
      bloomThreshold: 0.7,
    },
  },
  // ── ここから R8 追加の10ステージ(scratchpad/r8-stages.json 準拠、verdict.fix 反映済み) ──
  {
    id: 'okujou',
    name: '屋上',
    subtitle: '真昼のヘリポートを奪い合う低遮蔽戦',
    seed: 101,
    size: 56,
    obstacleCount: 20,
    maxHeight: 2,
    botCount: 5,
    palette: {
      sky: '#86c0ea',
      // fogはmatch側でskyへ35% lerpされるため事前補正(#a8cfe8を逆算)。lerp後に意図のヘイズ色へ着地する
      fog: '#b7d7e7',
      floor: '#4a4e54',
      wall: '#6d747d',
      obstacle: '#a2aab2',
      accent: '#ffd028',
      mood: 'day',
      grassKind: 'none',
      particle: 'none',
      silhouette: 'skyline',
      lightColor: '#fffaf0',
      lightIntensity: 1.7,
      ambientIntensity: 0.9,
      fogDensity: 0.007, // 全ステージ最低=高所の澄んだ空気
      emissiveAccent: false,
      turbidity: 2,
      rayleigh: 1.2,
      mieCoefficient: 0.003,
      elevation: 62, // 全ステージ最高の中天。影が短く落下縁の視認を妨げない
      azimuth: 190,
      exposure: 0.95,
      environmentIntensity: 0.95,
    },
  },
  {
    id: 'saisekiba',
    name: '採石場',
    subtitle: '段丘の高低差を制する立体戦',
    seed: 107,
    size: 64,
    obstacleCount: 22,
    maxHeight: 4.5,
    botCount: 5,
    palette: {
      sky: '#bcd2da',
      fog: '#d9c39c', // 粉塵の暖色霞(lerp後は乾いたベージュへ)
      floor: '#c4a06a',
      wall: '#9c6b3d',
      obstacle: '#5f6871',
      accent: '#ffd23f',
      mood: 'overcast',
      grassKind: 'dry',
      grassDensity: 0.35,
      particle: 'dust',
      particleAmount: 0.9,
      silhouette: 'ridge',
      groundFog: 0.35,
      lightColor: '#ffe9c2',
      lightIntensity: 1.55,
      ambientIntensity: 0.85,
      fogDensity: 0.012,
      emissiveAccent: false,
      // verdict.fix: 澄んだ青空だと粉塵設定と矛盾+kunren/nakaniwaと被るため、白茶の粉塵ドームへ(4→7, 1.4→1.1, 0.006→0.008)
      turbidity: 7,
      rayleigh: 1.1,
      mieCoefficient: 0.008,
      elevation: 38,
      azimuth: 225,
      exposure: 0.98, // 明るい床#c4a06aの白飛び防止に1.0未満
      environmentIntensity: 0.8,
    },
  },
  {
    id: 'chikurin',
    name: '竹林',
    subtitle: '木漏れ日の竹柱に紛れる忍び合い',
    seed: 113,
    size: 52,
    obstacleCount: 32,
    maxHeight: 5,
    botCount: 4,
    palette: {
      sky: '#c4ddb8',
      fog: '#b5cfa3', // 全ステージ唯一の緑fog(苔緑もや)
      floor: '#5a7a4e',
      wall: '#4e5f42',
      obstacle: '#96ad5a',
      accent: '#c94f36',
      mood: 'day',
      grassKind: 'blade',
      grassDensity: 0.9,
      particle: 'firefly',
      silhouette: 'none',
      groundFog: 0.35,
      lightColor: '#fff2cf',
      lightIntensity: 1.5,
      ambientIntensity: 0.85,
      fogDensity: 0.018,
      emissiveAccent: false,
      // verdict.fix: 青ドームだと緑fogと継ぎ目が出るため、kairou式の白霞地平へ脱色(3→7, 1.6→1.0, 0.004→0.006)
      turbidity: 7,
      rayleigh: 1.0,
      mieCoefficient: 0.006,
      elevation: 44,
      azimuth: 135,
      exposure: 0.95,
      environmentIntensity: 0.8,
    },
  },
  {
    id: 'tanada',
    name: '棚田',
    subtitle: '水鏡の段丘を畦づたいに詰める低遮蔽戦',
    seed: 127,
    size: 60,
    obstacleCount: 22,
    maxHeight: 2.5,
    botCount: 5,
    palette: {
      sky: '#e2d5ae',
      fog: '#ddd6a0', // verdict.fix: sakyuu(#e8d6a8)とヘイズ署名が被るため緑金寄りへ分離
      floor: '#6e8a7c',
      wall: '#7d7261',
      obstacle: '#6f5b3e',
      accent: '#a8c94f',
      mood: 'dusk',
      grassKind: 'reed',
      particle: 'firefly',
      silhouette: 'ridge',
      groundFog: 0.35,
      lightColor: '#ffdda0',
      lightIntensity: 1.45,
      ambientIntensity: 0.8,
      fogDensity: 0.012,
      emissiveAccent: false,
      // verdict.fix: elevation24では空が淡金にならずsky/フォグ/光色と乖離するため14へ+turbidity5→7(安全域12以上は維持)
      turbidity: 7,
      rayleigh: 1.9,
      mieCoefficient: 0.006,
      mieDirectionalG: 0.8,
      elevation: 14,
      azimuth: 255,
      exposure: 1.0,
      environmentIntensity: 1.05, // 水鏡の高反射IBL。床が中明度なので露出1.0でも破綻しない
      bloomStrength: 0.55,
    },
  },
  {
    id: 'misaki',
    name: '岬灯台',
    subtitle: '海風の岬に立つ白灯台の攻防',
    seed: 131,
    size: 58,
    obstacleCount: 20,
    maxHeight: 4,
    botCount: 5,
    palette: {
      sky: '#8fc3e8',
      fog: '#c2dcea',
      floor: '#a8b28e',
      wall: '#d8dde2',
      obstacle: '#75858f', // verdict.fix: #8a9aa4は床と1.30:1で溶けるため明度分離(1.71:1)を確保
      accent: '#e8442e',
      mood: 'day',
      grassKind: 'none',
      particle: 'dust',
      silhouette: 'skyline',
      groundFog: 0.3,
      lightColor: '#fff6e2',
      lightIntensity: 1.5,
      ambientIntensity: 0.85,
      fogDensity: 0.01,
      emissiveAccent: false,
      turbidity: 4,
      rayleigh: 2.2, // verdict.fix: kouwanの霞んだ港湾空から「岬の深い青」へ分離(1.7→2.2)
      mieCoefficient: 0.004,
      elevation: 33,
      azimuth: 220,
      exposure: 1.0,
      environmentIntensity: 0.85, // 白壁#d8dde2のIBL焼き込みを抑え雪原型白飛びを回避
    },
  },
  {
    id: 'haieki',
    name: '廃駅',
    subtitle: '朝霧に沈む貨車列の遭遇戦',
    seed: 137,
    size: 62,
    obstacleCount: 26,
    maxHeight: 3.5,
    botCount: 5,
    palette: {
      sky: '#d9d3c4',
      fog: '#d5cfc0',
      floor: '#8a8478',
      wall: '#6f695f',
      obstacle: '#8c4f38',
      accent: '#4fae6b', // 場内信号灯の信号緑(唯一未使用の色相)
      mood: 'overcast',
      grassKind: 'none',
      particle: 'dust',
      silhouette: 'skyline',
      // R13: 0.9は足元が白飛びして貨車が消える。朝霧の「沈む」情感は残しつつ0.55へ
      groundFog: 0.55,
      lightColor: '#ffe3b8',
      lightIntensity: 1.35,
      ambientIntensity: 0.85,
      fogDensity: 0.018, // size62前後ならこのままで良い(verdict注記)
      emissiveAccent: true,
      // verdict.fix: rayleigh1.5だと天頂が青く「乳白の朝霧空」にならないため暖白の朝靄へ(7→9, 1.5→0.9)
      turbidity: 9,
      rayleigh: 0.9,
      mieCoefficient: 0.008,
      mieDirectionalG: 0.82,
      elevation: 18,
      azimuth: 110,
      exposure: 1.02,
      environmentIntensity: 0.75,
      bloomThreshold: 0.8, // verdict.fix: 影側・霧中の信号灯だけが柔らかく滲む閾値
    },
  },
  {
    id: 'kyokoku',
    name: '峡谷',
    subtitle: '赤岩の高壁が絞る三本の射線',
    seed: 139,
    size: 66,
    obstacleCount: 20,
    maxHeight: 6,
    botCount: 5,
    palette: {
      sky: '#8fc3e8',
      fog: '#d9ae88', // 赤土埃(lerp後は乾いたベージュ靄)
      floor: '#c07f58', // verdict.fix: #b5734fは障害物と1.48:1で溶けるため明度分離(1.77:1)を確保
      wall: '#8a4a30',
      obstacle: '#a25a38',
      accent: '#2f9ec4',
      mood: 'day',
      grassKind: 'dry',
      grassDensity: 0.35,
      particle: 'dust',
      particleAmount: 0.9,
      silhouette: 'mountain',
      groundFog: 0.3,
      lightColor: '#fff2dc',
      lightIntensity: 1.75,
      ambientIntensity: 0.65, // 昼マップ最低=谷底の深い影
      fogDensity: 0.009,
      emissiveAccent: false,
      // verdict.fix: 空を宣言色「乾いた深青」に整合させnakaniwa/sakyuuと署名を分離(4→5, 1.1→1.4, 0.004→0.006)
      turbidity: 5,
      rayleigh: 1.4,
      mieCoefficient: 0.006,
      elevation: 55,
      azimuth: 240, // verdict.fix: 195だとnakaniwa(200)と太陽方向がほぼ重複するため空白帯の240へ
      exposure: 0.92,
      environmentIntensity: 0.85,
    },
  },
  {
    id: 'kohan',
    name: '湖畔',
    subtitle: '桟橋と岩陰を縫う静かな水辺',
    seed: 149,
    size: 54,
    obstacleCount: 16,
    maxHeight: 3,
    botCount: 4,
    palette: {
      sky: '#c2d3d6',
      fog: '#c6d3cd',
      floor: '#7a8a6e',
      wall: '#8a7a63',
      obstacle: '#5f6156', // verdict.fix: #8b887aは床と1.04:1でほぼ無分離のため濡れ花崗岩の暗灰へ(1.70:1)
      accent: '#aacc33',
      mood: 'overcast',
      grassKind: 'reed',
      grassDensity: 0.5,
      particle: 'firefly',
      silhouette: 'ridge',
      groundFog: 0.35,
      lightColor: '#f0efe2',
      lightIntensity: 1.25,
      ambientIntensity: 0.95,
      fogDensity: 0.015,
      emissiveAccent: false,
      turbidity: 6,
      rayleigh: 1.3,
      mieCoefficient: 0.006,
      elevation: 40,
      azimuth: 215,
      exposure: 0.98,
      environmentIntensity: 0.75,
    },
  },
  {
    id: 'kuko',
    name: '空港エプロン',
    subtitle: '西日の誘導路を貫く超長射線',
    seed: 151,
    size: 70,
    obstacleCount: 12,
    maxHeight: 3,
    botCount: 6,
    palette: {
      sky: '#c4c3b6', // verdict.fix: 寒色#bfc9d4だとsoukoと姉妹サムネに見えるため暖グレー空へ(fog lerpとも整合)
      fog: '#cfc9ba',
      floor: '#a8a29a',
      wall: '#7b756c',
      obstacle: '#5c6672',
      accent: '#ffce1f', // ICAO誘導路イエロー
      mood: 'dusk',
      grassKind: 'none',
      particle: 'dust',
      silhouette: 'skyline',
      groundFog: 0.35,
      lightColor: '#ffdfa0', // verdict.fix: 西日として半歩暖色化(#ffe3ae→)
      lightIntensity: 1.5,
      ambientIntensity: 0.85,
      fogDensity: 0.008, // kouwan(0.009)より下=最長視程
      emissiveAccent: false,
      turbidity: 5,
      rayleigh: 2.4, // verdict.fix: 西空の暖グラデを強調しsoukoのニュートラル空と分離(2.0→2.4)
      mieCoefficient: 0.008,
      mieDirectionalG: 0.85, // verdict.fix: 西日ハロを指向的に(soukoの無ハロと差別化)
      elevation: 26,
      azimuth: 240,
      exposure: 1.0,
      environmentIntensity: 0.8,
      bloomStrength: 0.55,
    },
  },
  {
    id: 'onsengai',
    name: '湯けむり温泉街',
    subtitle: '湯気の切れ間を突く石畳の近接戦',
    seed: 157,
    size: 50,
    obstacleCount: 22,
    maxHeight: 4,
    botCount: 4,
    palette: {
      sky: '#c4d8d0',
      // R13: near-white(#dce6de)は湯気が画面全体を白霞させバグっぽい。緑白の霞へ半段落とす
      fog: '#cdd8d2',
      floor: '#8a938e', // verdict.fix: 暖灰#8a8378は木材障害物と溶けるため「空を映す濡れ石畳」の緑白へ(寒暖分離1.57:1)
      wall: '#5f4c3c',
      obstacle: '#8a6a4a',
      accent: '#4a74b4', // verdict.fix: #3a5f9eは障害物より暗く影の塊に見えるため半段明るい藍へ
      mood: 'dusk',
      grassKind: 'dry',
      grassDensity: 0.4,
      particle: 'none',
      silhouette: 'ridge',
      // R13: 湯けむりの足元霧。0.9は白飛びで石畳/敵が消えるため0.55へ(局所湯気演出に委ねる)
      groundFog: 0.55,
      lightColor: '#ffeed2',
      lightIntensity: 1.35,
      ambientIntensity: 0.85,
      fogDensity: 0.015, // verdict.fix: 0.02はsetsugenの深フォグと被るため0.015へ(湯気は局所演出に委ねる)
      emissiveAccent: false,
      turbidity: 6,
      rayleigh: 1.6,
      mieCoefficient: 0.008,
      elevation: 30,
      azimuth: 110,
      exposure: 1.0,
      environmentIntensity: 0.75,
    },
  },
  // ── ⑥ ゾンビモード専用ステージ z01〜z10(BO2ゾンビ的な 夜の街/炎/溶岩/廃墟/濃霧/血) ──
  // seed 163〜211 は既存20ステージと非衝突。mood は overcast(z03/z09=昼の灰霧)以外すべて night。
  // ゾンビの緑バイザーが赤グレードに沈まないよう grade.tint R≤1.10 / saturation≤1.05 を厳守。
  // grassKind は全て 'none'=草インスタンスを ember/lava/ash へ回して overdraw を抑える(R12軽量制約)。
  // z05/z10 は最重(溶岩+濃霧)のため particleAmount を絞り groundFogTop≤1.2 で加算オーバードローを制限。
  {
    id: 'z01',
    name: '夜の廃市',
    subtitle: 'ネオンの死んだ街路を徘徊する影',
    seed: 163,
    size: 58,
    obstacleCount: 24,
    maxHeight: 3.6,
    botCount: 8,
    palette: {
      sky: '#12141c',
      fog: '#16181f',
      floor: '#2a2c33',
      wall: '#22242b',
      obstacle: '#33373f',
      accent: '#ff7a2e',
      mood: 'night',
      grassKind: 'none',
      particle: 'ember',
      particleAmount: 0.8,
      silhouette: 'skyline',
      groundFog: 0.4,
      lightColor: '#7a86a8',
      lightIntensity: 0.6,
      ambientIntensity: 0.42,
      fogDensity: 0.02,
      emissiveAccent: true,
      turbidity: 14,
      rayleigh: 0.6,
      mieCoefficient: 0.02,
      elevation: 12,
      azimuth: 300,
      exposure: 1.02,
      environmentIntensity: 0.4,
      bloomThreshold: 0.72,
      grade: {
        tint: [1.05, 0.99, 1.04],
        contrast: 1.08,
        saturation: 0.94,
        vignette: 0.44,
        grain: 0.06,
      },
    },
  },
  {
    id: 'z02',
    name: '紅蓮区画',
    subtitle: '燃え崩れる街区を炎が舐める',
    seed: 167,
    size: 56,
    obstacleCount: 26,
    maxHeight: 4,
    botCount: 8,
    palette: {
      sky: '#1c1310',
      fog: '#241813',
      floor: '#2e2620',
      wall: '#26201b',
      obstacle: '#3a2c22',
      accent: '#ff5a24',
      mood: 'night',
      grassKind: 'none',
      particle: 'ember',
      particleAmount: 1.0,
      silhouette: 'skyline',
      groundFog: 0.45,
      lightColor: '#ff9a5c',
      lightIntensity: 0.75,
      ambientIntensity: 0.5,
      fogDensity: 0.024,
      emissiveAccent: true,
      turbidity: 15,
      rayleigh: 0.7,
      mieCoefficient: 0.022,
      elevation: 12,
      azimuth: 100,
      exposure: 1.06,
      environmentIntensity: 0.45,
      bloomStrength: 0.62,
      bloomThreshold: 0.7,
      grade: {
        tint: [1.1, 0.97, 0.9],
        contrast: 1.1,
        saturation: 1.02,
        vignette: 0.42,
        grain: 0.07,
      },
    },
  },
  {
    id: 'z03',
    name: '灰霧の廃港',
    subtitle: '灰混じりの濃霧に沈む廃埠頭',
    seed: 173,
    size: 64,
    obstacleCount: 22,
    maxHeight: 3.5,
    botCount: 8,
    palette: {
      sky: '#3a3d40',
      fog: '#34363a',
      floor: '#4a4c50',
      wall: '#3c3e42',
      obstacle: '#55585d',
      accent: '#8a9098',
      mood: 'overcast',
      grassKind: 'none',
      particle: 'ash',
      particleAmount: 0.9,
      silhouette: 'skyline',
      groundFog: 0.55,
      groundFogTop: 1.15,
      lightColor: '#b8bcc2',
      lightIntensity: 0.9,
      ambientIntensity: 0.6,
      fogDensity: 0.026,
      emissiveAccent: false,
      turbidity: 12,
      rayleigh: 0.9,
      mieCoefficient: 0.012,
      elevation: 13,
      azimuth: 140,
      exposure: 1.0,
      environmentIntensity: 0.6,
      grade: {
        tint: [1.0, 1.0, 1.02],
        contrast: 1.05,
        saturation: 0.9,
        vignette: 0.4,
        grain: 0.08,
      },
    },
  },
  {
    id: 'z04',
    name: '崩落聖堂',
    subtitle: '瓦礫と化した大聖堂の亡骸',
    seed: 179,
    size: 60,
    obstacleCount: 28,
    maxHeight: 5,
    botCount: 8,
    palette: {
      sky: '#14161d',
      fog: '#191b22',
      floor: '#2f2d2a',
      wall: '#3a362f',
      obstacle: '#47423a',
      accent: '#c9a24a',
      mood: 'night',
      grassKind: 'none',
      particle: 'ash',
      particleAmount: 0.8,
      silhouette: 'skyline',
      groundFog: 0.42,
      lightColor: '#8a8296',
      lightIntensity: 0.6,
      ambientIntensity: 0.45,
      fogDensity: 0.021,
      emissiveAccent: true,
      turbidity: 13,
      rayleigh: 0.7,
      mieCoefficient: 0.016,
      elevation: 12,
      azimuth: 220,
      exposure: 1.02,
      environmentIntensity: 0.42,
      bloomThreshold: 0.74,
      grade: {
        tint: [1.04, 1.0, 1.0],
        contrast: 1.08,
        saturation: 0.92,
        vignette: 0.46,
        grain: 0.07,
      },
    },
  },
  {
    id: 'z05',
    name: '溶岩坑道',
    subtitle: '地を裂く溶岩流の熱気地獄',
    seed: 181,
    size: 62,
    obstacleCount: 20,
    maxHeight: 4.5,
    botCount: 8,
    palette: {
      sky: '#1a0e0a',
      fog: '#2a140c',
      floor: '#2e1c14',
      wall: '#241611',
      obstacle: '#3a2018',
      accent: '#ff3a12',
      mood: 'night',
      grassKind: 'none',
      particle: 'lava',
      particleAmount: 0.4, // 最重ステージ=加算オーバードローを抑えるため火の粉を絞る
      silhouette: 'ridge',
      groundFog: 0.6,
      groundFogTop: 1.15,
      lightColor: '#ff7038',
      lightIntensity: 0.7,
      ambientIntensity: 0.5,
      fogDensity: 0.03,
      emissiveAccent: true,
      turbidity: 16,
      rayleigh: 0.6,
      mieCoefficient: 0.024,
      elevation: 12,
      azimuth: 90,
      exposure: 1.04,
      environmentIntensity: 0.45,
      bloomStrength: 0.6,
      bloomThreshold: 0.7,
      grade: {
        tint: [1.1, 0.95, 0.88],
        contrast: 1.12,
        saturation: 1.04,
        vignette: 0.48,
        grain: 0.06,
      },
    },
  },
  {
    id: 'z06',
    name: '血染めの精肉場',
    subtitle: '血の海に沈む屠殺場の暗渠',
    seed: 191,
    size: 52,
    obstacleCount: 26,
    maxHeight: 3.6,
    botCount: 8,
    palette: {
      sky: '#16101a',
      fog: '#1c1218',
      floor: '#2c2024',
      wall: '#241a1e',
      obstacle: '#382428',
      accent: '#b52a3a',
      mood: 'night',
      grassKind: 'none',
      particle: 'ash',
      particleAmount: 0.7,
      silhouette: 'none',
      groundFog: 0.5,
      lightColor: '#9a7080',
      lightIntensity: 0.55,
      ambientIntensity: 0.42,
      fogDensity: 0.022,
      emissiveAccent: true,
      turbidity: 14,
      rayleigh: 0.6,
      mieCoefficient: 0.018,
      elevation: 12,
      azimuth: 260,
      exposure: 1.0,
      environmentIntensity: 0.42,
      bloomThreshold: 0.74,
      grade: {
        tint: [1.08, 0.96, 0.98],
        contrast: 1.1,
        saturation: 0.98,
        vignette: 0.48,
        grain: 0.08,
      },
    },
  },
  {
    id: 'z07',
    name: '封鎖検問所',
    subtitle: '廃車のバリケードで塞がれた検問線',
    seed: 193,
    size: 66,
    obstacleCount: 24,
    maxHeight: 3.5,
    botCount: 8,
    palette: {
      sky: '#14161a',
      fog: '#191b20',
      floor: '#2b2d31',
      wall: '#23252a',
      obstacle: '#3a3d34',
      accent: '#ffb020',
      mood: 'night',
      grassKind: 'none',
      particle: 'ember',
      particleAmount: 0.7,
      silhouette: 'skyline',
      groundFog: 0.38,
      lightColor: '#8892a0',
      lightIntensity: 0.6,
      ambientIntensity: 0.45,
      fogDensity: 0.019,
      emissiveAccent: true,
      turbidity: 13,
      rayleigh: 0.7,
      mieCoefficient: 0.016,
      elevation: 12,
      azimuth: 320,
      exposure: 1.03,
      environmentIntensity: 0.45,
      bloomThreshold: 0.74,
      grade: {
        tint: [1.03, 1.0, 1.02],
        contrast: 1.07,
        saturation: 0.95,
        vignette: 0.42,
        grain: 0.06,
      },
    },
  },
  {
    id: 'z08',
    name: '残灯の地下街',
    subtitle: '点滅する街灯だけが残る地下商店街',
    seed: 197,
    size: 54,
    obstacleCount: 26,
    maxHeight: 3.4,
    botCount: 8,
    palette: {
      sky: '#0e1014',
      fog: '#141519',
      floor: '#26282d',
      wall: '#1e2024',
      obstacle: '#2e3138',
      accent: '#ffd45a',
      mood: 'night',
      grassKind: 'none',
      particle: 'ember',
      particleAmount: 0.6,
      silhouette: 'none',
      groundFog: 0.5,
      lightColor: '#ffcf88',
      lightIntensity: 0.5,
      ambientIntensity: 0.38,
      fogDensity: 0.023,
      emissiveAccent: true,
      turbidity: 16,
      rayleigh: 0.5,
      mieCoefficient: 0.022,
      elevation: 12,
      azimuth: 200,
      exposure: 1.05,
      environmentIntensity: 0.4,
      bloomStrength: 0.58,
      bloomThreshold: 0.72,
      grade: {
        tint: [1.06, 1.0, 0.96],
        contrast: 1.1,
        saturation: 0.96,
        vignette: 0.5,
        grain: 0.07,
      },
    },
  },
  {
    id: 'z09',
    name: '降灰の廃園',
    subtitle: '降り続く火山灰に埋もれる遊園地',
    seed: 199,
    size: 62,
    obstacleCount: 22,
    maxHeight: 4,
    botCount: 8,
    palette: {
      sky: '#4a4640',
      fog: '#444038',
      floor: '#55514a',
      wall: '#47433c',
      obstacle: '#605a52',
      accent: '#a86a3a',
      mood: 'overcast',
      grassKind: 'none',
      particle: 'ash',
      particleAmount: 1.0,
      silhouette: 'ridge',
      groundFog: 0.55,
      lightColor: '#c4bcae',
      lightIntensity: 0.95,
      ambientIntensity: 0.62,
      fogDensity: 0.024,
      emissiveAccent: false,
      turbidity: 11,
      rayleigh: 0.9,
      mieCoefficient: 0.012,
      elevation: 14,
      azimuth: 160,
      exposure: 0.98,
      environmentIntensity: 0.6,
      grade: {
        tint: [1.05, 1.0, 0.96],
        contrast: 1.04,
        saturation: 0.9,
        vignette: 0.4,
        grain: 0.09,
      },
    },
  },
  {
    id: 'z10',
    name: '業火の火口',
    subtitle: '溶岩と噴煙が渦巻く火口の縁',
    seed: 211,
    size: 60,
    obstacleCount: 18,
    maxHeight: 4.5,
    botCount: 8,
    palette: {
      sky: '#1c0f09',
      fog: '#301207',
      floor: '#2a1810',
      wall: '#20120c',
      obstacle: '#38211a',
      accent: '#ff4718',
      mood: 'night',
      grassKind: 'none',
      particle: 'lava',
      particleAmount: 0.4, // 溶岩+濃霧の最重ステージ=火の粉を絞りオーバードローを制限
      silhouette: 'mountain',
      groundFog: 0.62,
      groundFogTop: 1.2,
      lightColor: '#ff6a30',
      lightIntensity: 0.72,
      ambientIntensity: 0.52,
      fogDensity: 0.03,
      emissiveAccent: true,
      turbidity: 18,
      rayleigh: 0.6,
      mieCoefficient: 0.026,
      elevation: 12,
      azimuth: 70,
      exposure: 1.06,
      environmentIntensity: 0.48,
      bloomStrength: 0.6,
      bloomThreshold: 0.7,
      grade: {
        tint: [1.1, 0.94, 0.86],
        contrast: 1.12,
        saturation: 1.05,
        vignette: 0.5,
        grain: 0.06,
      },
    },
  },
];

// ⑥ ゾンビモード専用ステージのID一覧(z01〜z10)。string[] にして modes.ts の GameMode 順序に非依存。
export const ZOMBIE_STAGE_IDS: readonly string[] = [
  'z01',
  'z02',
  'z03',
  'z04',
  'z05',
  'z06',
  'z07',
  'z08',
  'z09',
  'z10',
];

// モード名でステージ集合を切り替える。'zombie' はゾンビ専用ステージのみ、
// それ以外(既存の対戦モード)はゾンビ用を除いた従来20ステージを返す。
// mode を string で受けることで modes.ts の GameMode 定義に依存しない。
export function stagesForMode(mode: string): StageDef[] {
  const isZombieStage = (s: StageDef): boolean => ZOMBIE_STAGE_IDS.includes(s.id);
  return mode === 'zombie' ? STAGES.filter(isZombieStage) : STAGES.filter((s) => !isZombieStage(s));
}

export function stageById(id: string): StageDef {
  const def = STAGES.find((s) => s.id === id);
  if (!def) throw new Error(`unknown stage: ${id}`);
  return def;
}
